[nextcloud]
user = runner
group = runner
listen = /run/php/nc-fpm.sock
listen.owner = www-data
listen.group = www-data
pm = static
pm.max_children = 8
php_admin_value[memory_limit] = 512M
php_admin_value[apc.enable_cli] = 1
