codecov:
  notify:
    after_n_builds: 5

comment:
  after_n_builds: 5
  require_changes: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch: off
